/*
Pulze.ai API

At Pulze it's our mission to supercharge today's workforce with AI to maximize the world's prosperity. We are doing so by enabling companies of any size to securely leverage Large Language Models (LLM) and easily build AI features into their apps. Our enterprise platform has access to all best in class LLMs and can route user requests to the most relevant model to get the highest quality response at the best price thanks to our smart meta model. End users can leverage pre-built applications, such as our Marketing AI product, or build custom apps on top of the Pulze Platform.

We are a VC Funded, early stage startup based in San Francisco.

The version of the OpenAPI document: 0.1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface Auth0PostRegistrationRequest
 */
export interface Auth0PostRegistrationRequest {
    /**
     * 
     * @type {string}
     * @memberof Auth0PostRegistrationRequest
     */
    'created_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof Auth0PostRegistrationRequest
     */
    'email': string;
    /**
     * 
     * @type {boolean}
     * @memberof Auth0PostRegistrationRequest
     */
    'email_verified'?: boolean;
    /**
     * 
     * @type {object}
     * @memberof Auth0PostRegistrationRequest
     */
    'extra_info'?: object;
    /**
     * 
     * @type {string}
     * @memberof Auth0PostRegistrationRequest
     */
    'family_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof Auth0PostRegistrationRequest
     */
    'given_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof Auth0PostRegistrationRequest
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof Auth0PostRegistrationRequest
     */
    'nickname'?: string;
    /**
     * 
     * @type {string}
     * @memberof Auth0PostRegistrationRequest
     */
    'phone_number'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Auth0PostRegistrationRequest
     */
    'phone_verified'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Auth0PostRegistrationRequest
     */
    'picture'?: string;
    /**
     * 
     * @type {string}
     * @memberof Auth0PostRegistrationRequest
     */
    'user_id': string;
}

