/*
Pulze.ai API

At Pulze it's our mission to supercharge today's workforce with AI to maximize the world's prosperity. We are doing so by enabling companies of any size to securely leverage Large Language Models (LLM) and easily build AI features into their apps. Our enterprise platform has access to all best in class LLMs and can route user requests to the most relevant model to get the highest quality response at the best price thanks to our smart meta model. End users can leverage pre-built applications, such as our Marketing AI product, or build custom apps on top of the Pulze Platform.

We are a VC Funded, early stage startup based in San Francisco.

The version of the OpenAPI document: 0.1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ConversationShareRequest
 */
export interface ConversationShareRequest {
    /**
     * If this playground was started from another existing conversation.
     * @type {string}
     * @memberof ConversationShareRequest
     */
    'continuation_of'?: string;
    /**
     * A list (of list) of Request IDs of all the messages that need to be shared in the playground.
     * @type {Array<Array<string>>}
     * @memberof ConversationShareRequest
     */
    'ids': Array<Array<string>>;
    /**
     * Set to True/False if you want it available for anyone with the link, or only members within the organization
     * @type {boolean}
     * @memberof ConversationShareRequest
     */
    'is_public'?: boolean;
}

