/*
Pulze.ai API

At Pulze it's our mission to supercharge today's workforce with AI to maximize the world's prosperity. We are doing so by enabling companies of any size to securely leverage Large Language Models (LLM) and easily build AI features into their apps. Our enterprise platform has access to all best in class LLMs and can route user requests to the most relevant model to get the highest quality response at the best price thanks to our smart meta model. End users can leverage pre-built applications, such as our Marketing AI product, or build custom apps on top of the Pulze Platform.

We are a VC Funded, early stage startup based in San Francisco.

The version of the OpenAPI document: 0.1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PaymentDetailsBalance } from './payment-details-balance';
import { SubscriptionPaused } from './subscription-paused';
import { UserDetails } from './user-details';

/**
 * 
 * @export
 * @interface FrontendSettings
 */
export interface FrontendSettings {
    /**
     * Balance details
     * @type {PaymentDetailsBalance}
     * @memberof FrontendSettings
     */
    'balance': PaymentDetailsBalance;
    /**
     * The currency of the user. Currently only \"USD\".
     * @type {string}
     * @memberof FrontendSettings
     */
    'currency': FrontendSettingsCurrencyEnum;
    /**
     * False when it\'s the user\'s first login/signup for an organization
     * @type {boolean}
     * @memberof FrontendSettings
     */
    'did_onboarding_setup': boolean;
    /**
     * True if the email was verified
     * @type {boolean}
     * @memberof FrontendSettings
     */
    'email_verified': boolean;
    /**
     * Date of last accepted Privacy Policy
     * @type {string}
     * @memberof FrontendSettings
     */
    'privacy_accepted'?: string;
    /**
     * Returned to the frontend when the subscription has been paused for any reason.
     * @type {SubscriptionPaused}
     * @memberof FrontendSettings
     */
    'subscription_paused'?: SubscriptionPaused;
    /**
     * Date of last accepted Terms of Service
     * @type {string}
     * @memberof FrontendSettings
     */
    'terms_accepted'?: string;
    /**
     * The basic information for the user
     * @type {UserDetails}
     * @memberof FrontendSettings
     */
    'user_details': UserDetails;
}

type FrontendSettingsCurrencyEnum = 'USD'


