/*
Pulze.ai API

At Pulze it's our mission to supercharge today's workforce with AI to maximize the world's prosperity. We are doing so by enabling companies of any size to securely leverage Large Language Models (LLM) and easily build AI features into their apps. Our enterprise platform has access to all best in class LLMs and can route user requests to the most relevant model to get the highest quality response at the best price thanks to our smart meta model. End users can leverage pre-built applications, such as our Marketing AI product, or build custom apps on top of the Pulze Platform.

We are a VC Funded, early stage startup based in San Francisco.

The version of the OpenAPI document: 0.1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ChoicesProperty } from './choices-property';
import { PulzeEngineResponseMetadata } from './pulze-engine-response-metadata';
import { PulzeEngineTokens } from './pulze-engine-tokens';

/**
 * The response of any request to Completions or Chat Completions endpoints. This is a generic class!
 * @export
 * @interface PulzeEngineResponse
 */
export interface PulzeEngineResponse {
    /**
     * 
     * @type {ChoicesProperty}
     * @memberof PulzeEngineResponse
     */
    'choices'?: ChoicesProperty;
    /**
     * Creation timestamp
     * @type {number}
     * @memberof PulzeEngineResponse
     */
    'created'?: number;
    /**
     * This ID gets generated by the database when we save the request
     * @type {string}
     * @memberof PulzeEngineResponse
     */
    'id'?: string;
    /**
     * Metadata of the response
     * @type {PulzeEngineResponseMetadata}
     * @memberof PulzeEngineResponse
     */
    'metadata'?: PulzeEngineResponseMetadata;
    /**
     * The fully qualified model name used by PulzeEngine
     * @type {string}
     * @memberof PulzeEngineResponse
     */
    'model': string;
    /**
     * The type of response object
     * @type {string}
     * @memberof PulzeEngineResponse
     */
    'object': PulzeEngineResponseObjectEnum;
    /**
     * Tokens used
     * @type {PulzeEngineTokens}
     * @memberof PulzeEngineResponse
     */
    'usage'?: PulzeEngineTokens;
}

type PulzeEngineResponseObjectEnum = 'text_completion' | 'chat.completion'


