/*
Pulze.ai API

At Pulze it's our mission to supercharge today's workforce with AI to maximize the world's prosperity. We are doing so by enabling companies of any size to securely leverage Large Language Models (LLM) and easily build AI features into their apps. Our enterprise platform has access to all best in class LLMs and can route user requests to the most relevant model to get the highest quality response at the best price thanks to our smart meta model. End users can leverage pre-built applications, such as our Marketing AI product, or build custom apps on top of the Pulze Platform.

We are a VC Funded, early stage startup based in San Francisco.

The version of the OpenAPI document: 0.1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PulzeDefaultModelData
 */
export interface PulzeDefaultModelData {
    /**
     * A description of the model
     * @type {string}
     * @memberof PulzeDefaultModelData
     */
    'description': string;
    /**
     * Extra model settings inferred from namespace
     * @type {string}
     * @memberof PulzeDefaultModelData
     */
    'at'?: string;
    /**
     * The max_tokens for this model
     * @type {number}
     * @memberof PulzeDefaultModelData
     */
    'context_window': number;
    /**
     * The name of the model. Can belong to many providers
     * @type {string}
     * @memberof PulzeDefaultModelData
     */
    'model': string;
    /**
     * The fully qualified (namespaced) model name
     * @type {string}
     * @memberof PulzeDefaultModelData
     */
    'namespace': string;
    /**
     * The owner of the model. Sometimes, for a provider/model combination, many instances exist, trained on different data
     * @type {string}
     * @memberof PulzeDefaultModelData
     */
    'owner'?: string;
    /**
     * The provider for the model.
     * @type {string}
     * @memberof PulzeDefaultModelData
     */
    'provider'?: string;
    /**
     * The most recent data this model has been trained with
     * @type {string}
     * @memberof PulzeDefaultModelData
     */
    'until'?: string;
    /**
     * A URL to the model\'s page or more informatino
     * @type {string}
     * @memberof PulzeDefaultModelData
     */
    'url': string;
}

