/*
Pulze.ai API

At Pulze it's our mission to supercharge today's workforce with AI to maximize the world's prosperity. We are doing so by enabling companies of any size to securely leverage Large Language Models (LLM) and easily build AI features into their apps. Our enterprise platform has access to all best in class LLMs and can route user requests to the most relevant model to get the highest quality response at the best price thanks to our smart meta model. End users can leverage pre-built applications, such as our Marketing AI product, or build custom apps on top of the Pulze Platform.

We are a VC Funded, early stage startup based in San Francisco.

The version of the OpenAPI document: 0.1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ToolCall } from './tool-call';

/**
 * 
 * @export
 * @interface RoleContentChatChoice
 */
export interface RoleContentChatChoice {
    /**
     * 
     * @type {string}
     * @memberof RoleContentChatChoice
     */
    'content'?: string;
    /**
     * 
     * @type {string}
     * @memberof RoleContentChatChoice
     */
    'role': RoleContentChatChoiceRoleEnum;
    /**
     * If `tool_choice` parameter was passed, and the model supports it, this will return a list of the different calls/functions used.
     * @type {Array<ToolCall>}
     * @memberof RoleContentChatChoice
     */
    'tool_calls'?: Array<ToolCall>;
}

type RoleContentChatChoiceRoleEnum = 'user' | 'assistant' | 'system'


