/*
Pulze.ai API

At Pulze it's our mission to supercharge today's workforce with AI to maximize the world's prosperity. We are doing so by enabling companies of any size to securely leverage Large Language Models (LLM) and easily build AI features into their apps. Our enterprise platform has access to all best in class LLMs and can route user requests to the most relevant model to get the highest quality response at the best price thanks to our smart meta model. End users can leverage pre-built applications, such as our Marketing AI product, or build custom apps on top of the Pulze Platform.

We are a VC Funded, early stage startup based in San Francisco.

The version of the OpenAPI document: 0.1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { GetTableSortParams } from './get-table-sort-params';

/**
 * 
 * @export
 * @interface StatsRequest
 */
export interface StatsRequest {
    /**
     * The list of API Keys we want to filter for. Leave the list empty to disable filtering (and return data for all apps) instead.
     * @type {Array<string>}
     * @memberof StatsRequest
     */
    'app_ids'?: Array<string>;
    /**
     * 
     * @type {{ [key: string]: boolean; }}
     * @memberof StatsRequest
     */
    'cumulative'?: { [key: string]: boolean; };
    /**
     * The earliest date we are searching for.
     * @type {string}
     * @memberof StatsRequest
     */
    'date_from': string;
    /**
     * The latest date we are searching for.
     * @type {string}
     * @memberof StatsRequest
     */
    'date_to'?: string;
    /**
     * The sorting parameters for the query
     * @type {Array<GetTableSortParams>}
     * @memberof StatsRequest
     */
    'params'?: Array<GetTableSortParams>;
}

