/*
Pulze.ai API

At Pulze it's our mission to supercharge today's workforce with AI to maximize the world's prosperity. We are doing so by enabling companies of any size to securely leverage Large Language Models (LLM) and easily build AI features into their apps. Our enterprise platform has access to all best in class LLMs and can route user requests to the most relevant model to get the highest quality response at the best price thanks to our smart meta model. End users can leverage pre-built applications, such as our Marketing AI product, or build custom apps on top of the Pulze Platform.

We are a VC Funded, early stage startup based in San Francisco.

The version of the OpenAPI document: 0.1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * For any given subscription, this represents the set of available features
 * @export
 * @interface SubscriptionSettings
 */
export interface SubscriptionSettings {
    /**
     * Support from Marketing team (? TBD)
     * @type {boolean}
     * @memberof SubscriptionSettings
     */
    'customer_success': boolean;
    /**
     * Allows to fine-tune models
     * @type {boolean}
     * @memberof SubscriptionSettings
     */
    'fine_tuning': boolean;
    /**
     * Flowz Feature
     * @type {boolean}
     * @memberof SubscriptionSettings
     */
    'flowz'?: boolean;
    /**
     * Dynamic LLM routing using KG
     * @type {boolean}
     * @memberof SubscriptionSettings
     */
    'llm_routing'?: boolean;
    /**
     * Maximum number of apps that can be created
     * @type {number}
     * @memberof SubscriptionSettings
     */
    'max_apps': number;
    /**
     * A human-readable format of max_apps. Example: \'Infinite\' or \'1000\' or \'None\'
     * @type {string}
     * @memberof SubscriptionSettings
     */
    'max_apps_readable': string;
    /**
     * The maximum number of tokens that can be _generated_, for each billing period (month)
     * @type {number}
     * @memberof SubscriptionSettings
     */
    'max_tokens': number;
    /**
     * A human-readable format of max_tokens. Example: \'50bn\' or \'+100M\'
     * @type {string}
     * @memberof SubscriptionSettings
     */
    'max_tokens_readable': string;
    /**
     * The Stripe PriceID for the monthly subscription
     * @type {string}
     * @memberof SubscriptionSettings
     */
    'monthly_price_id'?: string;
    /**
     * Price per MONTH -- same as in Stripe, here for display purposes
     * @type {number}
     * @memberof SubscriptionSettings
     */
    'monthly_price_usd'?: number;
    /**
     * The name for this subscription
     * @type {string}
     * @memberof SubscriptionSettings
     */
    'name': string;
    /**
     * Custom scoring of LLMs using KG
     * @type {boolean}
     * @memberof SubscriptionSettings
     */
    'personalized_llm_routing': boolean;
    /**
     * Allows the user to create and use Prompt-based Models
     * @type {boolean}
     * @memberof SubscriptionSettings
     */
    'prompt_models': boolean;
    /**
     * Allows the user to create and use Prompts
     * @type {boolean}
     * @memberof SubscriptionSettings
     */
    'prompts': boolean;
    /**
     * The level of support this user has access to
     * @type {string}
     * @memberof SubscriptionSettings
     */
    'support_level': SubscriptionSettingsSupportLevelEnum;
    /**
     * A human-readable format for the level of support offered
     * @type {string}
     * @memberof SubscriptionSettings
     */
    'support_level_readable': string;
    /**
     * The Stripe PriceID for the yearly subscription
     * @type {string}
     * @memberof SubscriptionSettings
     */
    'yearly_price_id'?: string;
    /**
     * Price per YEAR -- same as in Stripe, here for display purposes
     * @type {number}
     * @memberof SubscriptionSettings
     */
    'yearly_price_usd'?: number;
}

type SubscriptionSettingsSupportLevelEnum = 'community' | 'all'


